services:
  api:
    build:
      target: development
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_TEST_DB_NAME}
    ports:
      - "${WEB_HOST}:${TEST_PORT}:8000"
    volumes:
      - .:/app

  db:
    environment:
      - POSTGRES_DB=${POSTGRES_TEST_DB_NAME}
    volumes:
      - postgres-db-test:/var/lib/postgresql/data

volumes:
  postgres-db-test:
    driver: local
    name: ${PROJECT_NAME}-postgres-db-test
    external: false