services:
  api:
    build:
      target: development
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DEV_DB_NAME}
    ports:
      - "${WEB_HOST}:${DEV_PORT}:8000"
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  db:
    environment:
      - POSTGRES_DB=${POSTGRES_DEV_DB_NAME}
    volumes:
      - postgres-db-dev:/var/lib/postgresql/data

volumes:
  postgres-db-dev:
    driver: local
    name: ${PROJECT_NAME}-postgres-db-dev
    external: false